token_url = "https://identity.scisports.app/connect/token"
"grant_type": "password"
"username": "j.dirkx@fcdenbosch.nl"
"password": "faqvyg-9wIbfi-jajkex"
"client_id": "BridgeFootballGroupAPI"
"client_secret": ",%0y+ErrFWT|aP("
"scope": "api recruitment performance"

base_url = "https://api-recruitment.scisports.app"
